travis:
  secure:
    BINSTAR_TOKEN: RMdXBw2P0FXS9AsrAhfgkwUfc0uy2gVTKeTB9PpQXn2q4QnlwbE2+AL0o8w+FodWSePcvVNNr2knFDrgZdxRBfM+TGxSsfVA4Pv6bS+BKZicJyj/4qsgMOby/Lf2nhhYLUWjyPs8gXn99aXl+mip+iX7QMTjiky0N6hy74uGi2q8pF0ynt+6NP7lXgbzaX6f/bROavgrqJhdPX6z9n99+dIyBAI1qzkHliiEiq+E94jqwALQlk910eKwK8izm9e2FcZiA0Z7BO0VpvA7NkH5w+7JwFSCuhvev+pVlVWbEeAlM/aNW0hNji/rHa487Prs3JVSCTdcic2h1oUKuSIMpDwMDibDeg7lw1D27WufvaCipZgzbdwX7pJKCy6zXAZzH3a1Gq4K0068AvRYKhOKDGzuIfPEjoggTWFrvNGAeFNjG3UYyYECMfa5UzVVTmGiX2D1G3prdelReEM5HptkdBEQc1QLHga6PwAuIW8D4nJmWpKwJpXfww56kTNrsVJ2izpVTepO/kkRSilnd/s0i37yE3ZMWswbQW1i6MqWIsDaTnv15Qha96ghXT7uSpxVfgwkEVBxhOhsYcovY+Th5I0BhzBH2edHEgMEpzqXOtRS9nm4Brmam4YcRkzQp3CBFknIRxt96/OM4Og30lc3K3WTyCLFCuIpJLuJTqPKT5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
